remote_theme: "mmistakes/minimal-mistakes@4.24.0"
lang: ko-KR
timezone: Asia/Seoul

title: 코스피 상대 강도
repository:remaster5/remaster5.github.io

plugins:
  - jekyll-include-cache
  - jekyll-feed

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-include-cache
  - jekyll-feed

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: # true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

#analytics:
  #provider: "google-gtag"
  #google:
    #tracking_id: "G-Y37MGBP94B"
    #anonymize_ip: false # default
