name: Scrap KOSPI stock data and calculate RS rating all.

on:
  schedule:
    - cron: "45 6 * * 1-5"
  workflow_dispatch: {}
  
jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        persist-credentials: false
        fetch-depth: 0
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
    - name: Grant execute permission to KOSPI script
      run: chmod +x ./calc-kospi-rs.py
    - name: Grant execute permission to KOSDAQ script
      run: chmod +x ./calc-kosdaq-rs.py
    - name: Grant execute permission to KRX script
      run: chmod +x ./calc-krx-rs.py
    - name: Run KOSPI script
      run: |
        ./calc-kospi-rs.py
    - name: Run KOSDAQ script
      run: |
        ./calc-kosdaq-rs.py
    - name: Run KRX script
      run: |
        ./calc-krx-rs.py
    - name: Commits
      run: |
        git config --local user.email "remaster5@gmail.com"
        git config --local user.name "remaster5"
        git add .
        git commit -m "[AUTO] Daily KOSPI RS rating"
    - name: Push
      uses: ad-m/github-push-action@master
      with:
        branch: 'main'
        github_token: ${{ secrets.GITHUB_TOKEN }}
